sudo: required
dist: trusty
language: node_js

node_js:
    - "8.10.0"

before_install:
  - npm i -g npm

install:
  - npm ci

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - npm run test

email:
  recipients:
    - syytest11@163.com
  on_success: always
  on_failure: always